name: Docker Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted # Specify the self-hosted runner for this job

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: docker build -t kavindujayarathna/calculator-website:1.2 .

      - name: Push Docker image to Docker Hub
        run: docker push kavindujayarathna/calculator-website:1.2

      # Additional steps for deployment to EC2 instance
      - name: Deploy to EC2 instance
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Add your private SSH key to GitHub Secrets
        run: |
          ssh -i "$SSH_PRIVATE_KEY" ec2-user@43.204.143.105 "docker pull kavindujayarathna/calculator-website:1.2"
          ssh -i "$SSH_PRIVATE_KEY" ec2-user@43.204.143.105 "docker stop calculator-website || true"
          ssh -i "$SSH_PRIVATE_KEY" ec2-user@43.204.143.105 "docker rm calculator-website || true"
          ssh -i "$SSH_PRIVATE_KEY" ec2-user@43.204.143.105 "docker run -d --name calculator-website -p 80:80 kavindujayarathna/calculator-website:1.2"
