name: Docker Publish and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Build and tag Docker image
        run: docker build -t calculator-image .



      - name: Docker Run
        run: |
           docker run --name -p 80:80 calculator-app calculator-image